### ISSUE TITLE
Error running in Jupyter Anaconda

### ISSUE THREAD

**Issue by RicardoAsk** [ideas-lab-nus/data-science-bldg-energy-efficiency#1]
Hi there... I'm just trying to run the code... however, I got this error:
Do I miss something?

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-31cf35f44be3> in <module>
      1 #import modules
      2 
----> 3 from gensim.models import KeyedVectors
      4 import gensim
      5 import os

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/gensim/__init__.py in <module>
      3 """
      4 
----> 5 from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils # noqa:F401
      6 import logging
      7 

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/gensim/models/__init__.py in <module>
      5 
      6 # bring model classes directly into package namespace, to save some typing
----> 7 from .coherencemodel import CoherenceModel  # noqa:F401
      8 from .hdpmodel import HdpModel  # noqa:F401
      9 from .ldamodel import LdaModel  # noqa:F401

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/gensim/models/coherencemodel.py in <module>
     34 from gensim import interfaces, matutils
     35 from gensim import utils
---> 36 from gensim.topic_coherence import (segmentation, probability_estimation,
     37                                     direct_confirmation_measure, indirect_confirmation_measure,
     38                                     aggregation)

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/gensim/topic_coherence/probability_estimation.py in <module>
     10 import logging
     11 
---> 12 from gensim.topic_coherence.text_analysis import (
     13     CorpusAccumulator, WordOccurrenceAccumulator, ParallelWordOccurrenceAccumulator,
     14     WordVectorsAccumulator)

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/gensim/topic_coherence/text_analysis.py in <module>
     19 
     20 from gensim import utils
---> 21 from gensim.models.word2vec import Word2Vec
     22 
     23 logger = logging.getLogger(__name__)

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/gensim/models/word2vec.py in <module>
    133 
    134 from gensim.utils import keep_vocab_item, call_on_class_only
--> 135 from gensim.models.keyedvectors import Vocab, Word2VecKeyedVectors
    136 from gensim.models.base_any2vec import BaseWordEmbeddingsModel
    137 

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/gensim/models/keyedvectors.py in <module>
    181 from scipy import stats
    182 from gensim.utils import deprecated
--> 183 from gensim.models.utils_any2vec import (
    184     _save_word2vec_format,
    185     _load_word2vec_format,

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/gensim/models/utils_any2vec.py in <module>
    196 #
    197 try:
--> 198     from gensim.models._utils_any2vec import (
    199         compute_ngrams as _compute_ngrams_cy,
    200         compute_ngrams_bytes as _compute_ngrams_bytes_cy,

__init__.pxd in init gensim.models._utils_any2vec()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by MahmoudAbdelRahman** [comment]
Hi @RicardoAsk , 

I think this might be an issue with Numpy. So, can you uninstall then re-install Numpy? 
[Please refer to this stackoverflow issue](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp)
```
pip uninstall numpy
pip install numpy
```
Also, can you generate a `requirements.txt` file? 
```pip freeze > requirements.txt```
Let me know how it goes
